/**
 * Icons map for dynamic icon usage
 * Import this file when you need to access icons by string name
 */

import {
  UserIcon,
  UsersIcon,
  BookIcon,
  IdCardIcon,
  PhoneIcon,
  ChartIcon,
  ChecklistIcon,
  MapIcon,
  BackpackIcon,
  SwordsIcon,
  PawIcon,
  WalletIcon,
  NotesIcon,
  SettingsIcon,
  HomeIcon,
  WifiIcon,
  WifiOffIcon,
  BatteryFullIcon,
  BatteryLowIcon,
  BatteryMediumIcon,
  CrownIcon,
  PlusIcon,
  MinusIcon,
  XIcon,
  TrashIcon,
  SendIcon,
  SearchIcon,
  CheckIcon,
  ArrowLeftIcon,
  DiceIcon,
  MessageIcon,
  EditIcon,
} from './Icons';

// Export all icons as a map for dynamic use
export const Icons = {
  user: UserIcon,
  users: UsersIcon,
  book: BookIcon,
  idCard: IdCardIcon,
  phone: PhoneIcon,
  chart: ChartIcon,
  checklist: ChecklistIcon,
  map: MapIcon,
  backpack: BackpackIcon,
  swords: SwordsIcon,
  paw: PawIcon,
  wallet: WalletIcon,
  notes: NotesIcon,
  settings: SettingsIcon,
  home: HomeIcon,
  wifi: WifiIcon,
  wifiOff: WifiOffIcon,
  batteryFull: BatteryFullIcon,
  batteryLow: BatteryLowIcon,
  batteryMedium: BatteryMediumIcon,
  crown: CrownIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  x: XIcon,
  trash: TrashIcon,
  send: SendIcon,
  search: SearchIcon,
  check: CheckIcon,
  arrowLeft: ArrowLeftIcon,
  dice: DiceIcon,
  message: MessageIcon,
  edit: EditIcon,
};

export default Icons;
